name: 'Update'

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'dist/**'

  schedule:
    # JST 4:00 AM
    - cron: '0 19 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: '${{ secrets.BOT_GITHUB_TOKEN }}'

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: 'go.sum'

      - name: Generate
        run: go run ./

      - name: Pull
        run: git pull

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: '🔄 Update'
          commit_author: 'StarryBlueSky-bot <97773209+StarryBlueSky-bot@users.noreply.github.com>'
